[package]
name = "miden-crypto"
version = "0.2.0"
description = "Miden Cryptographic primitives"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/crypto"
documentation = "https://docs.rs/miden-crypto/0.2.0"
categories = ["cryptography", "no-std"]
keywords = ["miden", "crypto", "hash", "merkle"]
edition = "2021"
rust-version = "1.67"

[[bench]]
name = "hash"
harness = false

[[bench]]
name = "smt"
harness = false

[[bench]]
name = "store"
harness = false

[features]
default = ["blake3/default", "std", "winter_crypto/default", "winter_math/default", "winter_utils/default"]
std = ["blake3/std", "winter_crypto/std", "winter_math/std", "winter_utils/std"]

[dependencies]
blake3 = { version = "1.3", default-features = false }
winter_crypto = { path = "../winterfell/crypto", package = "winter-crypto", default-features = false }
winter_math = { path = "../winterfell/math", package = "winter-math", default-features = false }
winter_utils = { path = "../winterfell/utils/core", package = "winter-utils", default-features = false }
serde = { version = "1.0.117", default-features = true, features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
proptest = "1.1.0"
rand_utils = { path = "../winterfell/utils/rand", package = "winter-rand-utils" }
