[package]
name = "miden-processor"
version = "0.5.0"
description = "Miden VM processor"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
categories = ["emulators", "no-std"]
keywords = ["miden", "virtual-machine"]
edition = "2021"
rust-version = "1.67"

[lib]
bench = false
doctest = false

[features]
concurrent = ["winter-prover/concurrent", "std"]
default = ["std"]
internals = []
std = ["vm-core/std", "winter-prover/std", "log/std"]

[dependencies]
log = "0.4.14"
vm-core = { package = "miden-core", path = "../core", version = "0.5", default-features = false }
winter-prover = { package = "winter-prover", path = "../winterfell/prover", default-features = false }
serde = { version = "1.0.117", default-features = false, features = ["derive"] }

[dev-dependencies]
logtest = { version = "2.0", default-features = false  }
miden-assembly = { package = "miden-assembly", path = "../assembly", version = "0.5", default-features = false }
rand-utils = { package = "winter-rand-utils", path = "../winterfell/utils/rand" }
winter-fri = { package = "winter-fri", path = "../winterfell/fri" }
winter-utils = { package = "winter-utils", path = "../winterfell/utils/core" }
