[package]
name = "miden-verifier"
version = "0.5.0"
description="Miden VM execution verifier"
authors = ["miden contributors"]
readme="README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
categories = ["cryptography", "no-std"]
keywords = ["miden", "stark", "verifier", "zkp"]
edition = "2021"
rust-version = "1.67"

[lib]
bench = false
doctest = false

[features]
default = ["std"]
std = ["air/std", "vm-core/std", "winter-verifier/std"]

[dependencies]
air = { package = "miden-air", path = "../air", version = "0.5", default-features = false }
vm-core = { package = "miden-core", path = "../core", version = "0.5", default-features = false }
winter-verifier = { package = "winter-verifier",path = "../winterfell/verifier", default-features = false }
