[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "Polygon Miden VM"

[output.katex]
[output.html]
git-repository-url = "https://github.com/0xPolygonMiden/miden-vm/"

[output.linkcheck]
warning-policy = "ignore"

[preprocessor.katex]
